
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVISA DOLAR NUMBER\n    statement : conversion statement\n              | conversion\n    \n    conversion : NUMBER DIVISA DIVISA DOLAR\n    '
    
_lr_action_items = {'NUMBER':([0,2,7,],[3,3,-3,]),'$end':([1,2,4,7,],[0,-2,-1,-3,]),'DIVISA':([3,5,],[5,6,]),'DOLAR':([6,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,2,],[1,4,]),'conversion':([0,2,],[2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> conversion statement','statement',2,'p_statement_list','server.py',48),
  ('statement -> conversion','statement',1,'p_statement_list','server.py',49),
  ('conversion -> NUMBER DIVISA DIVISA DOLAR','conversion',4,'p_conversion','server.py',58),
]
